### ISSUE TITLE
Upload repo

### ISSUE THREAD

**Issue by jonnyhotchkiss** [hopbit/sonic-pi-autosave#1]
Hi! This is more of a question than an issue... how do you update your repo?
Eg when do you push to web, and also how? 
Is it a manual cmd from a cli or gui, or some sort of CI/CD?

Just curious, thinking about how to use (and edit) mine.

BR 🙏

**Comment by hopbit** [comment]
Hi @jonnyhotchkiss.

If you look into the commit history you will know that I haven't published any new history for more than a few years now :)

When I was doing it, it was more for fun and because of curiosity how the state of the buffers was stored and where. If I remember correctly it's being stored under %userprofile%\.sonicpi dir.

When I was pushing it to this repo I was doing it manually and probably was  using Git Bash for Windows.

Hope I've been able to help you :)
